"""Tests for the Ollama provider."""

from types import SimpleNamespace

import pytest
from ollama import ResponseError

from agent_workbench.errors import CompletionError
from agent_workbench.providers.ollama import OllamaProvider


def test_provider_returns_model_response(monkeypatch) -> None:
    """Return the text generated by the Ollama client."""

    def fake_chat(**kwargs):
        return SimpleNamespace(message=SimpleNamespace(content="provider working"))

    monkeypatch.setattr("agent_workbench.providers.ollama.chat", fake_chat)

    provider = OllamaProvider(model_name="test-model")

    assert provider.complete([]) == "provider working"


def test_connection_error_is_translated(monkeypatch) -> None:
    """Translate an Ollama connection failure into an application error."""

    def fake_chat(**kwargs) -> None:
        raise ConnectionError

    monkeypatch.setattr("agent_workbench.providers.ollama.chat", fake_chat)

    provider = OllamaProvider(model_name="test-model")

    with pytest.raises(
        CompletionError,
        match="Unable to connect to Ollama",
    ):
        provider.complete([])


def test_missing_model_error_is_translated(monkeypatch) -> None:
    """Provide a clear error when the configured model is unavailable."""

    def fake_chat(**kwargs) -> None:
        raise ResponseError("model not found", 404)

    monkeypatch.setattr("agent_workbench.providers.ollama.chat", fake_chat)

    provider = OllamaProvider(model_name="missing-model")

    with pytest.raises(
        CompletionError,
        match="Model 'missing-model' is not available",
    ):
        provider.complete([])
